linters:
  enable:
    - cyclop
    - dogsled
    - gci
    - exhaustive
    - gocognit
    - godot
    - govet
    - grouper
    - lll
    - nestif
    - revive
    - tagliatelle
    - unused
    - wsl
    - misspell
    - whitespace
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - deadcode
    - decorder
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - maintidx
    - makezero
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - varnamelen
    - wastedassign
    - wrapcheck

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
        bson: snake
        xml: snake
        avro: snake
        mapstructure: snake
  nestif:
    min-complexity: 7
  govet:
    check-shadowing: true
    enable-all: true
  gocognit:
    min-complexity: 35
  cyclop:
    max-complexity: 30
    package-average: 15.0