name: ci-release-image

on:
  release:
    types: [published]

jobs:
  build:
    name: versioned image
    needs: test
    runs-on: ubuntu-latest
    steps:
    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        name: speedtest
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: stevencyb/speedtest:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}